[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx-access.log
stderr_logfile=/var/log/nginx-error.log

[program:convex]
command=npx convex dev --typecheck disable --codegen enable
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/convex.log
stderr_logfile=/var/log/convex-error.log
environment=CONVEX_SITE_URL="%(ENV_CONVEX_SITE_URL)s",NODE_ENV="%(ENV_NODE_ENV)s",VLY_CONVEX_AUTH_ISSUER="%(ENV_VLY_CONVEX_AUTH_ISSUER)s"
